### ISSUE TITLE
Filters that repeat themselves.

### ISSUE THREAD

**Issue by blucobalto** [silvia-odwyer/pixels.js#4]
Hello,
Thank's for your job. The filter library is fabulous.
I just wanted to tell you that there are filters that repeat themselves.

**Filter name**
Neue = Blues
zapt = twilight
a = pixel_blue

**Functions**
neue_imgdata = blues_imgdata
zapt_imgdata = cool_twilight_imgdata
a = pixel_blue_imgdata

Also, the console.log is always used with the text:
offset called

Thanks a lots,
Blu

**Comment by silvia-odwyer** [comment]
Hi Blu, 
Thanks very much for letting me know about this,  it's greatly appreciated! 👍 I've just fixed this by replacing the repeat filters, and also removed the `a` filter as this was just for testing haha. Everything should be fixed now ✅ 
Thanks again!

**Comment by blucobalto** [comment]
Hi Silvia,
thanks for fixing the various filters.
I very much appreciated your availability 👍.
I hope I don't bother you with this request but
unfortunately I can't compile the "Pixels.js" library.
Please could you make available the Pixels.js library already compiled and usable by the browser.
In the "dist" folder I find the old version of Pixels.js
Thanks a lots.

Blu

---

After installing the required libraries with
`npm install`
I run
```
npm run-script build:browser
or
npm run build:browser
```

but I always get this error:

```
> y@1.0.0 build:browser
> webpack

/home/Apps/pixels.js-master/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read properties of undefined (reading 'properties')
    at module.exports (/home/Apps/pixels.js-master/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /home/Apps/pixels.js-master/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/Apps/pixels.js-master/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/Apps/pixels.js-master/node_modules/webpack/bin/webpack.js:156:2)
```

**Comment by silvia-odwyer** [comment]
Hi Blu, 
I've just updated the `dist` folder, it contains the latest version of Pixels.js now! 😄
I'll take a look into the build steps also and add some documentation for building the library in the future. It should help developers who wish to build the library ✅ Thanks very much again! 👍

**Comment by blucobalto** [comment]
Hi Silvia,
thanks for compiling the library.  👍 
It is a truly fantastic library and the effects are very creative.  :star2:
I am writing to you because I still have problems. 
I hope I'm not being too annoying. :bouquet:
I have tried to use the library in "dist" but I get an error.

`Uncaught ReferenceError: a is not defined`

To make it work, I removed the reference to the "a" filter from the compiled file.
Now it works but I ran into a couple of problems.

```
Neue === Solange
Sat_adj === Horizon
darkify === all black
incbrightness === all black
```

Thanks again for the effort you use to fix the library.
Blu

P.S.: sorry for my "English" I am Italian and I use a translator to write to you

**Comment by silvia-odwyer** [comment]
Hi Blu, 
That's no problem at all, I'm very glad to help of course! 😄 I've been working on some updates to the library, including:
- Updated the neue and removed the Horizon filter 
- Fixed the `incbrightness` and `darkify` bugs
- Added build instructions to the Readme file, so if you wish to build it, the instructions are now there too 👍 

I really appreciate the feedback, it means a lot! Thanks again 🎉 If you have other bugs to report, etc, be sure to let me know, I'm always happy to help 😄 👍

**Comment by blucobalto** [comment]
Hi Silvia,
perfect. 👍 
I was also able to compile. :smile:

Just a little bug:
"Horizon" and "a" filter still appears in the filter name list.
If I try to load all the filters when the program gets to Horizon or to "a" it crashes.

```
index.js

const getFilterNames = () => {
    let filter_dict = { ... "horizon": colour_tints.horizon_imgdata, ... "a": brightness_adj.a, .... }
    return filter_dict;
}
```

After removing the references of "Horizon" and "a" I have recompiled and everything works fine.

All filters work fine. :star2:

Thank you so much for your work. 🎉
Blu

**Comment by silvia-odwyer** [comment]
Hi Blu, 
That's fantastic, glad you're able to compile everything now 👍 Thanks for letting me know about the Horizon and a filters haha, I'll be sure to remove those from the filter name list. 
If you have any other questions, etc in the future don't hesitate to let me know. Thanks again 😄
